@startmindmap
*: Machine Learning
https://developers.google.cn/machine-learning/intro-to-ml/what-is-ml?hl=zh-cn;

** 机器学习系统的类型
***: 监督式学习
模型在看到大量数据以及正确答案后就能做出预测 然后在此基础上找出数据中 生成正确答案
核心概念
数据
模型
训练
正在评估
推理;
**** 回归
*****: 线性回归
在机器学习中 线性回归模型会找出 功能和 label
损失
平均绝对误差 (MAE 模型离离群值更远，但更接近 其他数据点 差值的绝对值总和 预测值与实际值之间的差异)
均方误差 (MSE 模型更接近离群值，但离大部分数据 其他数据点 平方差的总和 预测值与实际值之间的差异)
梯度下降法 一种以迭代方式找出产生权重和偏差的数学技术 选择损失最低的模型。梯度下降法找到最佳权重和偏差 重复以下过程进行多次用户定义的迭代 生成损失最低的模型;
****** 超参数
******* 学习速率：为 您设置的浮点数，它会影响 收敛。如果学习速率过低，模型可能需要很长时间 进行收敛。但是，如果学习速率过高， 会收敛，但会围绕权重和偏差弹跳，从而最大限度减少 损失。我们的目标是选择合适的学习速率 能够快速收敛。
******* 批次大小：是一个超参数， 指的是模型在更新权重之前处理的样本数 和偏差。您可能认为，模型应该计算每个 样本，然后再更新权重和偏差。但是，当 数据集包含数十万甚至数百万个样本， 全批量并不现实
******* 周期：在训练期间，一个周期表示 模型已处理训练集中的每个样本一次。例如，假设 一个包含 1,000 个样本和 100 个样本的小批次大小的训练集， 将对模型进行 10 次迭代， 完成一个周期。
*****: 逻辑回归S 型函数/Users/dontan/Downloads/live_rail_favorite.png
;
**** 分类
*** 非监督式学习
**** 聚类
*** 强化学习
*** 生成式 AI

@endmindmap