@startmindmap
* Blender
left side
** 常用快捷键
*** 添加 shift+a
*** 删除 x
***:==移动 g
----
方向移动 xyz
撤销 alt+g;
***:==缩放 s
----
方向缩放 xyz
撤销 alt+s;
***:==旋转 r
----
方向旋转 xyz
撤销 alt+r;
*** 视图切换 ~
*** 切换模式 tab
*** 未选中隐藏 shift+h
*** 聚焦选中元素 /
*** 反选 ctrl+i
*** 框选 b
*** 刷选 c
*** 透视 alt+z
*** 附着原点 alt+g
*** 取消父级选中物体 alt+p

** 名词解读
***:==法相/法线
指始终垂直某个面或者某切面的虚线,用来定义光线如何从曲面反弹的向量;


** 常用插件
***:==looptools
方便做简单形状处理;

** 经验
*** 尽量不要在物体模式下缩放,尽量在编辑下处理
*** 假如物体模式下做过缩放,需要应用下这个缩放 ctrl+a+scale
*** 需要将顶点接近 z 轴 0 位置,可以使用 s+z+0

right side
** 建模
***:==建模网站
cgtrader.com
free3d.com;

*** 编辑模式
**** 常用快捷键 
***** 打开/关闭左侧菜单栏(t)
***** 打开/关闭右侧侧菜单栏(n)
***** 圈选 alt+mouse double left click

**** 常用建模操作
*****:==菜单栏(ctrl+e)
更多点线面操作;
*****:==挤出extrude(e)
在选中的点线面向外挤出对应点线面，需要撤销两次，才能回到原来状态;
*****:==向内挤出insert(i)
在选中的点线面向内挤出对应点线面;
*****:==倒角bevel(ctrl+b)
用来为边线或拐角添加平滑效果的;
*****:==切割knife cut(k)
分割线面到新的形态;
*****:==环切loopcut(ctrl+r)
通过插入一组新的、与选中边交叉的循环边，切分一组循环面;
*****:==合并merge(m)
点和点、线和线、面和面合并，减少操作点线面;
*****:==断开rip(v)
将相邻点线面分离，类似展开效果，需要撤销两次，才能回到原来状态;
*****:==填充fill face(f)
任意选中的边或顶点创建三角面，只要它们可以组成一个或多个完整的线环;
*****:==桥接循环边(ctrl+e 桥接循环边)
使用面连接多组循环边;
*****:==分离separate(p)
分离选中元素，需要撤销两次，才能回到原来状态;

**** 辅助工具
*****:==衰减编辑 proportional
激活后,范围内元素会跟着移动,能让处理看上去跟平缓;
*****:==吸附工具 snapping
上方菜单栏吸附工具,点击下拉选项,选择面投射(根据需要),选中物体移动到需要吸附的目标;
***** 曲线建模 curve
*****:==晶格形变 lattice
绑定物体用于形变
----
1新建晶格,包裹需要解析的对象
2选中对象添加晶格修改器,绑定刚刚晶格,修改分辨率uvw,得到晶格框架
3选中晶格,进入编辑模式即可调整对象形状;
***** 旋绕工具 spin tool

**** 常用修改器
***** 表面细分 subdivision surface
***** 实体化 solidify
*****:==阵列 array
多个物体复制（物体偏移：空物体跟随）;
***** 简易形变 simple deform
*****:==曲线 curve
根据曲线可以制作如水管,蛇这类效果
修改点半径大小 alt+s
----
几何数据->倒角->深度
调整倒角半径 alt+s;
***** 镜像 mirror
*****:==置换 displace
修改器根据纹理的强度置换网格中的顶点。可以使用程序纹理或图像纹理.处理山峰起伏,石头表面等效果;
*****:==蒙皮 skin
适合做分叉模型
----
1添加平面,进入编辑模式,选择所有点,m合并到中心
2e挤出一条线
3添加蒙皮修改器
操控点缩放 ctrl+a;
***** 缩裹 shrinkwrap
***** 倒角 bevel
***** 布尔 boolean

** 渲染引擎

*** EEVEE
**** 优点:快,相对不占资源
**** 缺点:没有光线追踪,很多光线阴影的细节不佳,需要额外更多参数设置辅助

*** CYCLES
**** 优点:逼真,高级,能模拟出无力世界里非常细节的光线阴影
**** 缺点:慢,相对更消耗硬件资源

** 材质 PBR- Physically Based Rendering
*** 材质说明
****:==金属 metallic
金属一般设置0或1;
****:==糙度 roughness
需要更光滑设置糙度往0;
****:==次表面
决定模型是不是透光,如皮肤,窗帘的通透程度,一般不会调太大;
****:==次表面半径
决定半透光散射的距离;
**** 次表面颜色
****:==高光
树枝越大,反射越大,高光越亮;
****:==光泽
用于布料的部分,调到1,有天鹅绒的效果,控制皱褶反光反射数量,越大越明显;
****:==IOR折射率
透明材质常用光折射率,网上有提供资料;
****:==透射
打开,iOR折射率和透射粗糙度才起作用;
****:==透射粗糙度
物体内部粗糙度,可以做毛玻璃;

*** 材质节点
**** 纹理坐标:负责告诉机器用什么坐标系映射
**** 映射:负责调整材质位置旋转缩放
**** 载入图像纹理:可以改变图像投射的方式
**** 着色器:负责调整材质属性
**** 材质输出:负责输出最终结果

***:==材质网站
polyhaven.com
ambientcg.com;


** 粒子
*** 发射体粒子
*** 毛发粒子

** 场景灯光
***:==世界光
修改默认背景节点(常用)
天空纹理
渐变纹理
HDRI贴图(常用);
*** 场景光
****:==四种光源
点光
日光
聚光
面光(常用);
****:三点打光
主光，辅光，轮廓光;
****:打光经验
主光：主要对象照亮，确定方向，阴影方向
辅光：一般背面
明暗对比
冷暖对比;

** 动画
*** 时间轴动画
**** 插入关键帧
*** 形态键动画
**** 通过 0-1 控制从 a 形态变换到 b 形态
*** 摄像机动画
*** 骨骼绑定
*** 物体约束跟随
*** 动画修改器
**** 内置函数
**** 循环
**** 噪波
***:==粒子动画
渲染选择物体;


** 输出
*** eevee
**** 渲染:环境光,增加阴影细节
**** 辉光
**** 阔值:越低图片越蒙
**** 阴影:立方体尺寸越大,影子越圆滑,勾选柔和阴影,过渡更柔和,不勾选可以方便观察影子位置
*** CYCLES
**** 渲染采样
**** 灯光里的阴影,接触阴影,增加阴影细节
*** 经验
**** 勾选降噪,采样降低可以降低渲染时间
**** 压缩比例不需要调,15%比较正常

' left side

' ** 快捷键
' *** 编辑模式
' **** 打开/关闭左侧菜单栏(t)
' **** 打开/关闭右侧侧菜单栏(n)
@endmindmap